---
title: "Belfast Recovery College"
slug: "brc"
locations: 
  college: 
    title: "Recovery College"
    icon: "fa-map"
    url: "https://what3words.com/layers.envy.chin"
    address: |
      Recovery College, 
      Lanyon Building, 
      10 North Derby Street, 
      Belfast, 
      BT15 5HL
  teams: 
    title: "Online via Teams"
    icon: "fa-computer"
    url: "ms.teams.url"
    address: Online via Teams (link will be sent via email)
contact:
  address: |
    Recovery College, 
    Lanyon Building, 
    10 North Derby Street,
    Belfast 
    BT15 5HL
  telephone: 028 9504 3059
  email: RecoveryCollege@belfasttrust.hscni.net
links:
  www: https://belfasttrust.hscni.net/service/belfast-recovery-college/
  enrol: https://forms.office.com/pages/responsepage.aspx?id=3jCanNfYpEqWAEvnYl_2xcMHrn6YZTBIrC3Y1VelcQdUMlJONlVHNFlKR0hNRVNIMFBUSUtLVzI1WS4u
content:
  blurb: |
    WELCOME TO THE BELFAST RECOVERY COLLEGE COURSE PROGRAMME

    The Belfast Recovery College warmly welcomes you to enrol for our free wellbeing and mental health programme.  We have a range of face to face courses and webinars available.  
    
    All face to face courses will be held in:
    Belfast Recovery College, Lanyon Building, 10 North Derby Street Belfast BT15 5HL.

    Our education classes are open to everyone in the community of Belfast.

    For our courses all you have to do is enrol!


    Request an enrolment form by:

    Email: RecoveryCollege@belfasttrust.hscni.net


    Notify us of the courses you wish to enrol on: 
    E-mail: RecoveryCollege@belfasttrust.hscni.net


    Face to face and online:
    If you are unable to attend, please let us know, so another student can avail of your place.
    

    ATTENDING OUR WEBINARS 
    
    We recommend accessing our webinars on a PC, Laptop or Mac computer. It may be possible to access our webinars on other devices but we cannot be sure they are compatible with all devices, especially older or less powerful devices.
    
    
    Here at the Belfast Recovery College we use Microsoft Teams to deliver our webinars. The Belfast HSC Trust are making you aware that if you wish to participate in Recovery College Education classes via Webinars and have a personal Microsoft Teams Account or an organisational Microsoft Teams Account your email address may be visible to the other students during the course you are attending. 
    
    
    We would also like to make you aware if you choose to participate in the chat box during the course a record of the chat will be retained in Teams chat history which could be viewed by the students registered to attend that course. During the course and up to 5 minutes at the end of the course, you will have the option to delete any messages.  
    
    
    If you receive confirmation that you have reserved a space on one of our webinars an invitation to join the webinar will be sent to your registered email address the day before the course is due to run.  In this email a step by step guide will be included explaining how to open an “In Private” or “In Cognito” web browser to ensure your email address is not visible to the other student participating in the course and also guidance on how to delete any messages you share.  
    
    
    We understand attending new courses can be daunting, therefore we would like to offer you support. If you require any support or would like to speak to one of our peers who can talk you through the course aims, objectives and content please do not hesitate to contact us by email at RecoveryCollege@belfasttrust.hscni.net or give us a call on 028 9504 3059.
    
    
    Please note by enrolling for a course including an on-line application you are consenting to the terms of how the classes operate in the Belfast Recovery College.  

---
